using System;
using System.Collections.Generic;
using System.Text;



namespace InventoryApp
{
 /// <summary>
 /// list of material types 
 /// </summary>
 enum TypeOfMaterials
    {
        Stone,
        Sterling,
        Gold,
        Copper,
    }
/// <summary>
/// list of locations for location types
/// </summary>
    enum LocationID
    {
        Retailer,
        Online,
        Stock,
    }
    
    /// <summary>
    /// This is a raw material that can be sold as an individual piece
    /// or combined with other materials to create new pieces. Unique inventory numbers are generated, and wholesale and retail amounts are calculated, 
    /// and the user can indicate when the material is sold.
    /// </summary>
    class Element
    {
        private static int lastInventoryNumber = 0;
        
        #region Properties
        /// <summary>
        /// Raw material type of the element
        /// </summary>
        public TypeOfMaterials Material { get; set; }

        /// <summary>
        /// Weight of the element in grams
        /// </summary>
        public int Weight { get; set; }

        /// <summary>
        /// Retail price of item
        /// </summary>
        public decimal RPrice { get; private set; }

        /// <summary>
        /// Wholesale price of item
        /// </summary>
        public decimal WSPrice { get; set; }

        /// Autogenerated inventory number for the raw materials
        /// </summary>
        public int InventoryNumber { get; }

        /// <summary>
        /// Date acquired into inventory
        /// </summary>
        public DateTime DateAcquired { get; private set; }

        /// <summary>
        /// Location of the inventory item, stock, retail shop, online
        /// </summary>
        public LocationID Location { get; set; }

        public string SoldStatus { get; private set; }


        #endregion


        #region Constructor

        public Element()
        {
            InventoryNumber = ++lastInventoryNumber;
            DateAcquired = DateTime.Now;
        }
        #endregion


        #region Methods
        /// <summary>
        /// Calculate retail price
        /// </summary>
        /// <param name="markup">Price markup for retail</param>
        public void MakeRetail(decimal markup)
    
        {
            RPrice = WSPrice * markup;
        }

        internal void MakeRetail()
        {
            throw new NotImplementedException();
        }

        #endregion
    }
}